from pathlib import Path


BASE_PATH = Path().cwd()
MAPS_PATH = BASE_PATH / "maps" / "tmx"

FPS = 60


SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 1000

INTERACTIVE_WINDOW_WIDTH = 1000
STATS_BOX_WIDTH = SCREEN_WIDTH - INTERACTIVE_WINDOW_WIDTH

NUM_CELLS = 29
NUM_ROWS = SCREEN_HEIGHT // NUM_CELLS
NUM_COLS = INTERACTIVE_WINDOW_WIDTH // NUM_CELLS
